[package]
name = "unmd"
version = "0.1.0"
edition = "2018"
authors = ["David Herberth <github@dav1d.de>"]

[dependencies]
dbus = "0.9"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.2"
either = "1"
